// fails_with="assertion failed"

function main() ~> Nothing {
    std::assert(false);
}
